version: '3.3'

services:
  app:
    image: hello-world:nodets
    build:
      context: .
    ports:
      - 80:3000
    volumes:
      - ./nodets-ws:/node/project/app
    command: sh -c "npm run start"
