version: '3.3'

services:
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSSWORD
      - POSTGRES_DB
    volumes:
      - ./sql/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql

  app:
    image: adding-a-db:nodets
    build:
      context: .
    volumes:
      - .:/node/project/app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - APP_PORT
    command: sh -c "./utilities/wait-for-it.sh pg:5432; npm run start"
    depends_on:
      - "pg"

  lb:
    image: jfahrer/lb:v3
    build:
      context: ./load_balancer
    depends_on:
      - "app"
    environment:
      - PROXY_UPSTREAM
    ports:
      - "80:80"

volumes:
  pg-data: