version: '3.3'

services:
  app:
    image: storing-requests:nodets
    build:
      context: .
    ports:
      - 80:3030
    volumes:
      - ./app:/node/project/app
    command: sh -c "npm run start"
